FROM    node:16.17

WORKDIR /app

EXPOSE  8080

CMD     ["/bin/bash", "-c", "npm install && npm run start:dev"]
# CMD     ["npm", "install"]
# CMD     ["npm", "run", "build"]
# CMD     ["npm" , "start"]
