FROM    node:16.13.2

WORKDIR /app

EXPOSE  3000

CMD     ["/bin/bash", "-c", "npm install && npm run start:dev"]
# CMD     ["npm", "install"]
# CMD     ["npm", "run", "build"]
# CMD     ["npm" , "start"]
